import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.css";
import "./styles/global.scss";
import Link from "next/link";
import Header from "./components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <footer className="footer bg-dark text-white py-4 mt-5">
          <div className="container text-center">
            <p>© 2024 Men&apos;s Style Hub. Where Quality Meets Style.</p>
          </div>
        </footer>
      </body>
    </html>
  );
}
